### ISSUE TITLE
Homepage - Driver

### ISSUE THREAD

**Issue by cwoz117** [cpsc-471/project#32]
- For Drivers
  - Should show active jobs
  - Something when there are none 
    - A message saying get to work
    - A history card showing completed jobs

**Comment by JVLelody** [comment]
FYI: I'm working on the history card showing completed jobs.

**Comment by JVLelody** [comment]
History card for showing completed jobs is done.

**Comment by JVLelody** [comment]
I'm not going to write a message to get to work. If they don't have any completed, it says "No completed jobs" (something along that line anyways)

**Comment by JVLelody** [comment]
I can do the show active jobs.

**Comment by JVLelody** [comment]
Actives jobs are shown. Problem is that there is a bug for viewing the details. I'm going to create a new issue and assign Chris + myself to it.
