### ISSUE TITLE
Market order requires an "accept contract" button

### ISSUE THREAD

**Issue by cwoz117** [cpsc-471/project#45]

**Comment by JVLelody** [comment]
Super easy (I think...), I'll do it tomorrow.

**Comment by cwoz117** [comment]
well, I mean I was assigned to it, and worked on it instead of my ENTI business plan... Check the top right when you find an issue, if its open its likely that someone created it from the project

Feel free to take issues that are unassigned! 👍

**Comment by cwoz117** [comment]
#63
