### ISSUE TITLE
- Open Contracts card needs to pull open contracts (Probably with AJAX but doesn't have to be)

### ISSUE THREAD

**Issue by benjaminlee1** [cpsc-471/project#55]

**Comment by JVLelody** [comment]
Check out: fill_active_orders.php. 
I've also updated the _CompanyHome.php so that these orders will show up. If it's what you wanted, then close this issue.

**Comment by cwoz117** [comment]
I don't know what you guys are referring to here

actions/fill_market.php Gets a list of all open workorders, and it looks like shining also made an
actions/fill_active_orders.php

Why do we have two actions for this @JVLelody ?

**Comment by JVLelody** [comment]
@cwoz117 
fill_active_orders = Driver sees the order he has decided to take on, however they are not completed. It's like his "to-do" list. 
fill_market = From what I got from your code, it's all the workorders that currently don't even have someone working on it (aka, there's no contract for that order yet). This should be viewable to every Company, Contract Employer, and Driver. This is the place where Driver/Contract Employer can look for jobs. 

Hence, they are different. The way they are displayed is also slightly different. The active orders have a "contract" in place between the company with the request and the driver doing the order. Hence it shows "Contract" and "Workorder details" and "payload details".
Market workorders don't have a contract worked out yet. It's just a job posting looking for a driver/employer to take. So it only shows "Workorder details" and "Payload Details".

**Comment by JVLelody** [comment]
Is this addressed? Can I close?

**Comment by cwoz117** [comment]
completed
