### ISSUE TITLE
Market sql query not correct

### ISSUE THREAD

**Issue by JVLelody** [cpsc-471/project#57]
Market is showing everything that is not completed. But must check that the job hasn't been taken by anyone yet (not in accepted orders).

**Comment by JVLelody** [comment]
Completed half way but stopped because I'm not sure if @benjaminlee1 is working on this.

**Comment by cwoz117** [comment]
#63 handles this tooo~~~

**Comment by benjaminlee1** [comment]
select * from WorkOrder where completed = 0 and workorder_no not in (select workorder_no from AcceptedOrders as a where a.company_id = company_id and a.payload_id = payload_id and a.workorder_no = workorder_no);

**Comment by benjaminlee1** [comment]
That query should select for all contracts that are not completed and not taken

**Comment by cwoz117** [comment]
completed
