### ISSUE TITLE
Bug in Driver - View completed jobs

### ISSUE THREAD

**Issue by JVLelody** [cpsc-471/project#58]
- Uses the AJAX thing but the <div> that shows up after you click a row in the table of completed jobs, it shows up on the TOP of the table. Not under the table row. 
- I don't know if it's because I'm using table and table elements don't allow this hidden thing. 
- Please fix T_T Much thanks! @cwoz117

**Comment by cwoz117** [comment]
#63 handles this as well :1st_place_medal:
