### ISSUE TITLE
Renaming Problems

### ISSUE THREAD

**Issue by cwoz117** [cpsc-471/project#66]
right now we have:
```
actions/fill_workorder.php
actions/fill_workorders.php
actions/fill_market.php
```

These all do fundamentally the same thing (Gets a workorder, and displays it with a button and hidden details dropdown)

For now we should rename these a bit more specifically so that we (*I*) won't be so damned confused as to what we're all doing.

Future plans should be to refactor this into a function so that we don't need 3 copies, but that sounds like a problem for a real company, not a db group.

**Ben:** I agree, the TAs won't care let's move on.

**Comment by JVLelody** [comment]
Quick question: You also have a fill_workorder.php file correct? The real code *conflict* occurs between my fill_workorder.php and your fill_workorder.php??

**Comment by cwoz117** [comment]
I do not, mine is fill_market.php, but I forgot the name of it after seeing fill_workorder, cause its really close to what I'm actually doing.

I'm not sure what kind of convention you guys wanna go with but I'd probably say we should make some changes like:

_file_data_function_

so "market_workorder_fill.php"

that way whatever files we are working on are grouped together. To that point, it may be better if we start putting these things in dirs:
```
/public/action/market/fill_workorders.php
```
ofc, that ruins any opportunity to reuse code. Idk, I'm arguing philosophies at this point, either works.

**Comment by JVLelody** [comment]
Renamed fill_workorder -> fill_completed_workorders.php

**Comment by cwoz117** [comment]
no way man, this is a BIG issue and its just gonna get worse
