### ISSUE TITLE
Profiles page

### ISSUE THREAD

**Issue by cwoz117** [cpsc-471/project#70]
It shows the username of the account twice, might be better if in one case we have the username (top left) while the name of the account is in the profile

<img width="1018" alt="screen shot 2017-12-07 at 5 40 28 pm" src="https://user-images.githubusercontent.com/11260741/33745719-d53648e4-db75-11e7-802b-98b8fde40655.png">

**Comment by benjaminlee1** [comment]
Did I not set it to the username's actual name?

**Comment by cwoz117** [comment]
I wouldn't call this a luxury fix, they are gonna see two values that TA's will see, 

I have the "go for gold" milestone for this purpose
