### ISSUE TITLE
Add Truck Form

### ISSUE THREAD

**Issue by cwoz117** [cpsc-471/project#71]
The form gives me red warning outlines before I entered text, its also so large that it forces me to scroll.

- Could we get away with fewer not null data in a vehicle?
- We could use <fieldsets> as well as smaller input boxes (I think theres a w3-small class or something like that we can add to <form> ```<form class="w3-small"> ``` which will make everything smaller.
<img width="942" alt="screen shot 2017-12-07 at 5 42 18 pm" src="https://user-images.githubusercontent.com/11260741/33745798-3fd20a58-db76-11e7-89ae-ba0f6b358366.png">

**Comment by benjaminlee1** [comment]
Okay I will also play around with this. Believe me I did not want to create this giant mess of a box with this many inputs, was only following ddl

**Comment by cwoz117** [comment]
This is a browser issue specific to FF, we're working it not during this assignment
