### ISSUE TITLE
Empty Truck view

### ISSUE THREAD

**Issue by cwoz117** [cpsc-471/project#72]
We probably want to just show a user who has a truck or two already, so its nbd. but if they want to create a user from scratch this looks kind of wonky.

```
<div class="w3-container w3-card w3-grey>You currently have not registered a truck</div> 
```
I'd probably suggest putting the text within a card div, and grey out the back, as if to show a space for trucks exists but doesn't have anything to show versus just text.
- the text also has no padding with the add-truck button so it seems weird.

PS: The add button looks awesome in my head, but its different than everything else I'v been enforcing to you guys, so I think I need to put my money where my mouth is. anyone who wants to make it a blue rounded button on the right/left of the container gets top points from me

<img width="606" alt="screen shot 2017-12-07 at 5 44 52 pm" src="https://user-images.githubusercontent.com/11260741/33745881-a88e5bb4-db76-11e7-8f27-e396f14e05c5.png">

**Comment by benjaminlee1** [comment]
I disagree, I like the way it looks right now and I have grown attached to that + while I was first learning to do the code with trucks.

**Comment by cwoz117** [comment]
I'm not saying I don't like it, the opposite!

I just think that its the only button on the site that looks like that, and thats a problem!
