### ISSUE TITLE
Homepage for Drivers

### ISSUE THREAD

**Issue by cwoz117** [cpsc-471/project#74]
Quick links only has one link, I think we should either:
1. Add more links to make it actually useful

or

2. Remove quick links entirely for drivers, instead just showing "completed jobs"
<img width="967" alt="screen shot 2017-12-07 at 5 53 23 pm" src="https://user-images.githubusercontent.com/11260741/33746008-8af2e2ea-db77-11e7-8992-3558dcbda5fd.png">

**Comment by JVLelody** [comment]
On it. I'm going to remove quick links and add it to a tab, similar for what it looks like for Company.

**Comment by cwoz117** [comment]
Works for me!

**Comment by JVLelody** [comment]
Ok~ I'll comment out the quick link code so if we need it again, we can just pull it up. But I feel like our site is too simple for quick links. LOL. But we can argue for it's ability to be extended in the future.
